spring.application.name=spring-boot-multi-tenancy-mysql

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
# Master DataSource Configuration (for users and tenants)
spring.datasource.master.url=jdbc:mysql://localhost:3301/master_db?createDatabaseIfNotExist=true
spring.datasource.master.username=yu71
spring.datasource.master.password=53cret
spring.datasource.master.driver-class-name=com.mysql.cj.jdbc.Driver
# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationMustBeLongEnoughForHS256Algorithm
jwt.expiration=86400000

# Server Configuration
server.port=8080
# Logging
logging.level.id.my.hendisantika.multitenancymysql=DEBUG
