spring.application.name=spring-boot-multi-tenancy-mysql
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
# Tenant 1 DataSource Configuration
spring.datasource.tenant1.jdbc-url=jdbc:mysql://localhost:3301/tenant1_db?createDatabaseIfNotExist=true
spring.datasource.tenant1.username=yu71
spring.datasource.tenant1.password=53cret
spring.datasource.tenant1.driver-class-name=com.mysql.cj.jdbc.Driver
# Tenant 2 DataSource Configuration
spring.datasource.tenant2.jdbc-url=jdbc:mysql://localhost:3301/tenant2_db?createDatabaseIfNotExist=true
spring.datasource.tenant2.username=yu71
spring.datasource.tenant2.password=53cret
spring.datasource.tenant2.driver-class-name=com.mysql.cj.jdbc.Driver
# Server Configuration
server.port=8080
